spring:
  application:
    name: netty-connector

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0

grpc:
  server:
    port: 9092

nacos:
  server-addr: localhost:8848
  namespace: public
  group: DEFAULT_GROUP

service:
  ip: ""

gateway:
  id: "connector-1"
  route:
    ttl-seconds: 300

netty:
  tcp:
    port: 7070

jwt:
  uid-key: uid
  public-key-path: "classpath:keys/jwt-public.pem"
