spring:
  application:
    name: message-pull-service
  datasource:
    url: ${value.datasource.url}
    username: ${value.datasource.username}
    password: ${value.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

grpc:
  server:
    port: 9094

  use-plaintext: true

nacos:
  server-addr: localhost:8848
  namespace: public
  group: DEFAULT_GROUP

service:
  ip: ""

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.com.pull.infrastructure.persistence.po
